apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  labels:
    app: {{ template "nfs-client-provisioner.name" . }}
    chart: {{ template "nfs-client-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Values.storage.storageclass.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storage.storageclass.default | quote }}
provisioner: {{ .Values.storage.provisioner.name }}
