# Default values for nfs-client-provisioner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/external_storage/nfs-client-provisioner
  tag: v2.0.1
  pullPolicy: IfNotPresent

storage:
  storageclass:
  # we specify a name for the storageClass
    name: managed-nfs-storage
    default: true
  # we specify a provisioner name, which will form part of the provisioner pod configuration
  provisioner:
    name: storageclasses/nfs-client
    # Must be declared!
    # nfs covers the location in which provisioned volumes will be created
    nfs:
      server: 192.168.0.1
      remotePath: /path/to/nfs

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true

test:
  enabled: false
  pod: nfs-client-provisioner-test
  pvc: nfs-client-provisioner-test

nodeSelector: {}

tolerations: []
