apiVersion: v1
kind: Service
metadata:
  name: {{ template "gerrit.fullname" . }}
  labels:
    app: {{ template "gerrit.name" . }}
    chart: {{ template "gerrit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.externalSshPort }}
      targetPort: {{ .Values.service.internalSshPort }}
      protocol: TCP
      name: ssh
  selector:
    app: {{ template "gerrit.name" . }}
    release: {{ .Release.Name }}
